### ISSUE TITLE
Investigate real time notebooks collaboration

### ISSUE THREAD

**Issue by Volscente** [Volscente/us_stocks#2]
[Reference Link](https://jupyterlab.readthedocs.io/en/stable/user/rtc.html#:~:text=Editors%20are%20not%20collaborative%20by,the%20link%20including%20the%20token.)

**Comment by aliabbasjaffri** [comment]
While researching for this, i was quite convinced that i saw something that really is 10 steps ahead of Jupyter. This tool is [Deepnote](https://deepnote.com/). I would highly encourage using it. Possibly for the sharing purpose, what we can do is use it in the beginning and then later we can [download the notebook in our repository](https://docs.deepnote.com/importing-and-exporing/export-a-notebook). Setting up jupyternotebook sharing on our own would require setting up a server and then exposing it and bla bla and that all can be easily avoided. 

What is your take on this?
